version: '3'

services:
  postgres_source:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: source_db
    ports:
      - "5432:5432"

  postgres_destination:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: destination_db
    ports:
      - "5433:5432"

  python_etl:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres_source
      - postgres_destination
